# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.GetDICE <- function(mat) {
    .Call('_SMAD_GetDICE', PACKAGE = 'SMAD', mat)
}

.GetPPN <- function(mat) {
    .Call('_SMAD_GetPPN', PACKAGE = 'SMAD', mat)
}

.SAINTexpress_int_impl <- function(inter_df, prey_df, bait_df, GO_df, f, R, L) {
    .Call('_SMAD_SAINTexpress_int_impl', PACKAGE = 'SMAD', inter_df, prey_df, bait_df, GO_df, f, R, L)
}

.SAINTexpress_spc_impl <- function(inter_df, prey_df, bait_df, GO_df, f, R, L) {
    .Call('_SMAD_SAINTexpress_spc_impl', PACKAGE = 'SMAD', inter_df, prey_df, bait_df, GO_df, f, R, L)
}

